#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const specsDir = path.join(process.cwd(),'specs');
const outDir = path.join(process.cwd(),'docs');
if(!fs.existsSync(outDir)) fs.mkdirSync(outDir,{recursive:true});

const files = fs.existsSync(specsDir) ? fs.readdirSync(specsDir).filter(f=>f.endsWith('.yaml')||f.endsWith('.yml')) : [];
const projects = [];
for(const f of files){
  try{
    const spec = yaml.load(fs.readFileSync(path.join(specsDir,f),'utf8'));
    projects.push({
      id: spec.id,
      name: spec.name,
      intent: spec.intent,
      summary: (spec.summary||'').split('\n').slice(0,2).join(' '),
      url: `./${spec.id}.html`
    });
  }catch(e){ console.warn('Skipping', f, e.message); }
}

// Use external shared CSS (docs/assets/style.css) generated by design_page.js
let cards = '';
for(const p of projects){
  cards += `<div class="index-card">\n  <h3>${p.name}</h3>\n  <p>${p.summary}</p>\n  <a class="cta" href="${p.url}">Open</a>\n</div>\n`;
}

const html = `<!doctype html>\n<html>\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>Project Intro Pages</title>\n<link rel="stylesheet" href="./assets/style.css">\n</head>\n<body>\n  <header class="index-hero">\n    <h1>Project Intro Pages</h1>\n    <p>Short introductions to selected projects — generated from spec files.</p>\n  </header>\n  <div class="index-container">\n    <div class="nav">\n      <a class="cta" href="#projects">Browse Projects</a>\n    </div>\n    <section id="projects" class="index-grid">\n      ${cards}\n    </section>\n    <div class="footer">Generated by project-intro-pages</div>\n  </div>\n</body>\n</html>`;

fs.writeFileSync(path.join(outDir,'index.html'), html, 'utf8');
console.log('Wrote', path.join(outDir,'index.html'));
